"""Assemble RESULTS.md from the JSON every run leaves behind.

    python scripts/report.py

Regenerating this file is the only way a number enters the repo's prose, so
nothing in RESULTS.md or the README is hand-typed: data/proc/prepare.json,
runs/cls_*/eval.json, runs/gradcam.json, runs/cluster.json, runs/labelfrac.json.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from wafermap.wm811k import CLASSES_9, DEFECT_CLASSES

R = Path("runs")
SWEEP = [("plain BCE", "cls_bce"), ("BCE + pos-weight^0.5", "cls_posw"),
         ("BCE + balanced sampling", "cls_bal"), ("focal + pos-weight^0.5", "cls_focal"),
         ("9-way softmax CE + balanced sampling", "cls_ce"),
         ("plain BCE, no augmentation", "cls_bce_noaug")]


def jload(p, d=None):
    p = Path(p)
    return json.loads(p.read_text()) if p.exists() else d


def table(rows, header):
    out = ["| " + " | ".join(str(h) for h in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |")
    return "\n".join(out) + "\n"


def f(x, n=3):
    return "-" if x is None else f"{x:.{n}f}"


def main():
    L = ["# Results", "",
         "Every number here is regenerated by `scripts/report.py` from the JSON "
         "each run writes. Nothing is typed in by hand, and nothing survives "
         "from the synthetic version of this repo.", ""]

    # ---------------------------------------------------------- dataset ----
    pr = jload("data/proc/prepare.json")
    if pr:
        L += ["## Dataset and split", "",
              table([["source", "WM-811K (`LSWMD.pkl`), 811,457 real wafer maps"],
                     ["labeled / unlabeled", f"{pr['n_labeled']:,} / {pr['n_unlabeled']:,}"],
                     ["lots", f"{pr['n_lots']:,}"],
                     ["distinct raw die-grid shapes", f"{pr['distinct_source_shapes']:,}"],
                     ["raw grid H (min/median/max)", " / ".join(map(str, pr["source_H"]))],
                     ["raw grid W (min/median/max)", " / ".join(map(str, pr["source_W"]))],
                     ["normalization", "area resize to 64x64, 2 channels "
                                       "(die coverage, fail density)"],
                     ["mean coverage / (pi/4)",
                      f"{pr['labeled']['mean_coverage_over_pi_4']:.4f} "
                      "(1.0 = the wafer disc exactly fills the frame)"],
                     ["split", "by `lotName`, whole lots, 70/15/15"],
                     ["lots per split", " / ".join(
                         f"{pr['lot_split_counts'][s]:,}" for s in ("train", "val", "test"))],
                     ["labeled wafers per split", " / ".join(
                         f"{pr['labeled']['split_counts'][s]:,}"
                         for s in ("train", "val", "test"))],
                     ["unlabeled wafers per split", " / ".join(
                         f"{pr['unlabeled']['split_counts'][s]:,}"
                         for s in ("train", "val", "test"))],
                     ["preprocessing wall clock", f"{pr['wall_s']:.0f} s (1x H100)"]],
                    ["", ""]),
              "", "Labeled wafers per class per split:", "",
              table([[c, f"{pr['class_counts'][c]:,}"] +
                     [f"{pr['labeled_split_by_class'][c][s]:,}"
                      for s in ("train", "val", "test")]
                     for c in CLASSES_9],
                    ["class", "total", "train", "val", "test"]), ""]

    # --------------------------------------------------- imbalance sweep ----
    rows, best_tag, best_path, best_val, sel = [], None, None, -1, {}
    for tag, path in SWEEP:
        e = jload(R / path / "eval.json")
        if not e:
            continue
        v, t = e["val"]["multilabel_8"], e["test"]["multilabel_8"]
        rows.append([tag, e["best_epoch"], f(v["macro_f1"]), f(t["macro_f1"]),
                     f(t["micro_f1"]), f(e["test"]["class9"]["weighted_f1"]),
                     f(e["test"]["class9"]["accuracy"], 4),
                     f(t["per_class"]["Near-full"]["f1"])])
        if v["macro_f1"] > best_val:
            best_val, best_tag, best_path = v["macro_f1"], tag, path
    if rows:
        L += ["## Class imbalance: a controlled sweep", "",
              "9,680 Edge-Ring wafers against 149 Near-full ones. Same "
              "architecture, same 60-epoch budget, same lot-level split; one "
              "knob changed per row. **Selected on val macro-F1, then evaluated "
              "once on test** -- the test column never picks anything.", "",
              table(rows, ["strategy", "best epoch", "val macro-F1",
                           "test macro-F1", "test micro-F1", "test 9-class wtd-F1",
                           "test 9-class acc", "test Near-full F1"]),
              "", f"Winning strategy on val: **{best_tag}** (`runs/{best_path}`).", ""]

    # --------------------------------------------- final model + seed noise ----
    sel = jload(R / "selection.json", {})
    if sel:
        L += ["## Final model, and what a rerun costs", "",
              "The val-winning strategy retrained on a longer schedule at a wider "
              "encoder, three seeds, one per H100.  Three seeds because a 0.01 "
              "difference between two strategies means nothing until you know what "
              "rerunning the *same* one costs.  Everything below is selected on "
              "val; `runs/cls_best` is the argmax of the val column.", "",
              table([[n, f(v["val_macro_f1"]), f(v["test_macro_f1"])]
                     for n, v in sel["candidates"].items()],
                    ["run", "val macro-F1", "test macro-F1"]), ""]
        if sel.get("seed_spread"):
            ss = sel["seed_spread"]
            L += [table([["seeds", ss["n_seeds"]],
                         ["test macro-F1 per seed",
                          ", ".join(f"{x:.4f}" for x in ss["test_macro_f1"])],
                         ["mean", f(ss["test_macro_f1_mean"], 4)],
                         ["range (max - min)", f(ss["test_macro_f1_range"], 4)],
                         ["9-class weighted-F1 mean", f(ss["test_weighted_f1_9_mean"], 4)],
                         ["9-class weighted-F1 range", f(ss["test_weighted_f1_9_range"], 4)]],
                        ["", ""]),
                  "", f"The seed range ({f(ss['test_macro_f1_range'], 4)}) is the "
                  "same size as the spread across imbalance strategies above, which "
                  "is why that sweep is reported as a null result rather than a "
                  "ranking.", ""]
        L += [f"Reported model: `{sel['selected']}`, mirrored to `runs/cls_best`.", ""]

    # ----------------------------------------------------- per-class F1 ----
    best = jload(R / "cls_best/eval.json") or (jload(R / f"{best_path}/eval.json")
                                               if best_path else None)
    if best:
        ml = best["test"]["multilabel_8"]
        L += ["## Per-class F1 on held-out lots", "",
              "The multi-label view: eight independent sigmoid heads, each with "
              "its own decision threshold fitted on **val** and frozen before "
              "test.", "",
              table([[c, f"{ml['per_class'][c]['support']:,}",
                      f(ml["per_class"][c]["precision"]), f(ml["per_class"][c]["recall"]),
                      f(ml["per_class"][c]["f1"]),
                      f(best["test"]["thresholds"][c], 2)]
                     for c in DEFECT_CLASSES],
                    ["class", "test support", "precision", "recall", "F1", "threshold"]),
              "",
              table([["multi-label macro-F1 (8 defect classes)", f(ml["macro_f1"])],
                     ["multi-label micro-F1", f(ml["micro_f1"])],
                     ["multi-label weighted-F1", f(ml["weighted_f1"])],
                     ["9-class macro-F1 (incl. `none`)",
                      f(best["test"]["class9"]["macro_f1"])],
                     ["9-class weighted-F1", f(best["test"]["class9"]["weighted_f1"])],
                     ["9-class accuracy", f(best["test"]["class9"]["accuracy"], 4)],
                     ["defect-vs-none detection F1", f(best["test"]["any_defect"]["f1"])],
                     ["test wafers", f"{best['test']['n']:,}"],
                     ["parameters", f"{best['n_params']:,}"],
                     ["training wall clock", f"{best['wall_min']:.1f} min (1x H100)"]],
                    ["metric", "value"]), ""]
        L += ["Row-normalized confusion (%), true down / predicted across:", "",
              table([[CLASSES_9[i]] +
                     [f"{100*v/max(sum(r),1):.1f}" for v in r]
                     for i, r in enumerate(best["test"]["confusion"])],
                    ["true \\ pred"] + CLASSES_9), ""]

    # -------------------------------------------------------- Grad-CAM ----
    gc = jload(R / "gradcam.json")
    if gc:
        L += ["## Grad-CAM, re-validated on real defects", "",
              "No localization ground truth ships with WM-811K, so four "
              "measurements with explicit chance levels stand in. `lift` is CAM "
              "mass on failed dies over the failed fraction of the wafer "
              "(chance 1.0); `centroid err` is in wafer radii, against the null "
              "of always answering the wafer centre; the deletion columns zero "
              "the failed dies under the top-10% CAM area and report the fall in "
              "the true-class probability, against deleting a random 10%.", "",
              table([[c, r["n"], f(r["fail_die_lift"], 2), f(r["r_cam"], 2),
                      f(r["r_fail"], 2), f(r["centroid_err_radii"], 2),
                      f(r["centroid_err_null_radii"], 2),
                      f(r["deletion_drop_cam"]), f(r["deletion_drop_random"])]
                     for c, r in gc["per_class"].items()],
                    ["class", "n", "fail-die lift", "CAM radius", "fail radius",
                     "centroid err", "null centroid err", "deletion drop (CAM)",
                     "deletion drop (random)"]),
              "",
              f"Mean fail-die lift **{gc['mean']['fail_die_lift']:.2f}x** chance; "
              f"CAM-radius vs fail-radius correlation across the eight class means "
              f"**{gc['mean']['r_corr_over_classes']:+.3f}**; deleting the top-10% "
              f"CAM area costs **{gc['mean']['deletion_drop_cam']:.3f}** of true-class "
              f"probability against **{gc['mean']['deletion_drop_random']:.3f}** for a "
              "random 10%.", ""]

    # ------------------------------------------------------- clustering ----
    cl = jload(R / "cluster.json")
    if cl:
        L += ["## Unknown-pattern clustering: purity on lots the clusters never saw", "",
              f"k-means is fitted on {cl['n_fit']:,} **unlabeled** wafer maps from "
              f"train lots. The centroids are then frozen and "
              f"{cl['n_eval_labeled_test']:,} labeled wafers from **test** lots -- "
              "held out of the classifier and of the clustering alike -- are "
              "assigned to their nearest centroid. Purity is measured there. "
              "`none` is "
              f"{100*cl['majority_baseline']:.1f}% of that set, so the "
              "defect-only column (the same measure restricted to the eight "
              "failure signatures) is the one that carries information.", ""]
        for name in cl["encoders"]:
            e = cl["encoders"][name]
            L += [f"**{name}** (dim {e['dim']}):", "",
                  table([[k, f(e["k"][k]["purity"], 4), f(e["k"][k]["purity_chance"], 4),
                          f(e["k"][k]["purity_defect_only"], 4),
                          f(e["k"][k]["purity_defect_only_chance"], 4),
                          f(e["k"][k]["nmi"], 4), f(e["k"][k]["nmi_defect_only"], 4),
                          f(e["k"][k]["ari"], 4)]
                         for k in sorted(e["k"], key=int)],
                        ["k", "purity", "purity (shuffled labels)",
                         "defect-only purity", "defect-only chance", "NMI",
                         "NMI (defect only)", "ARI"]), ""]

    ca = jload(R / "cluster_aug.json")
    if ca and cl:
        nice = {"d4": "d4 only", "geom": "d4 + translate/scale",
                "noise": "d4 + die dropout/salt noise"}
        rows_a = [[nice.get(n, n)] +
                  [f(ca["encoders"][n]["k"][k]["purity_defect_only"], 4)
                   for k in ("32", "128")] for n in ca["encoders"]]
        rows_a.append(["all three (the run above)"] +
                      [f(cl["encoders"]["simclr"]["k"][k]["purity_defect_only"], 4)
                       for k in ("32", "128")])
        rows_a.append(["raw-pixel PCA (floor)"] +
                      [f(cl["encoders"]["pixel_pca"]["k"][k]["purity_defect_only"], 4)
                       for k in ("32", "128")])
        L += ["### Which SimCLR view-invariance costs the defect signal", "",
              "Same encoder, same 25 epochs, same unlabeled pool, same k-means and "
              "the same held-out labeled probe -- only the augmentation set "
              "changes.  Defect-only purity:", "",
              table(rows_a, ["augmentations", "k=32", "k=128"]), ""]

    # -------------------------------------------------------------- SSL ----
    lf = jload(R / "labelfrac.json")
    if lf:
        fracs = sorted({float(x) for m in lf for x in lf[m]})
        nice = {"scratch": "from scratch", "ssl": "SimCLR init, finetuned",
                "probe": "SimCLR init, linear probe"}
        ssl = jload(R / "ssl/ssl.json", {})
        L += ["## Self-supervised pretraining: does it buy labels?", "",
              f"SimCLR on {ssl.get('n_unlabeled_train', 0):,} unlabeled wafer maps "
              f"from train lots ({ssl.get('wall_min', 0):.0f} min, 1x H100), then "
              "the same classifier head. Every cell gets the identical optimizer "
              "budget (6,000 steps) whatever fraction of labels it sees, so the "
              "comparison is about the initialization.", "",
              table([[nice.get(m, m)] +
                     [f(lf[m].get(f"{fr:g}", {}).get("test_macro_f1")) for fr in fracs]
                     for m in ("scratch", "ssl", "probe") if m in lf],
                    ["init"] + [f"{fr*100:g}% labels "
                                f"({lf.get('scratch', lf[list(lf)[0]]).get(f'{fr:g}', {}).get('n_train_labels', 0):,})"
                                for fr in fracs]), "",
              "Test multi-label macro-F1 over the 8 defect classes.", ""]

    Path("RESULTS.md").write_text("\n".join(L))
    print("wrote RESULTS.md", len("\n".join(L)), "chars")
    render_readme(pr, best, gc, cl, lf, rows, best_tag, sel,
                  jload(R / "ssl/ssl.json", {}))


def render_readme(pr, best, gc, cl, lf, sweep_rows, best_tag, sel, ssl):
    """README.tmpl.md + the run JSONs -> README.md.

    The README is a template with `{{key}}` holes; every hole is filled from a
    JSON a run wrote, and an unfilled hole is a hard error.  That is the only
    mechanism that keeps a number in the prose from drifting away from the
    number in the table beside it.
    """
    tmpl = Path("README.tmpl.md")
    if not tmpl.exists():
        return
    V = {}
    if pr:
        V |= {f"data.{k}": f"{pr[k]:,}" for k in
              ("raw_rows", "n_labeled", "n_unlabeled", "n_lots",
               "distinct_source_shapes")}
        V |= {"data.coverage_ratio": f"{pr['labeled']['mean_coverage_over_pi_4']:.4f}",
              "data.prep_s": f"{pr['wall_s']:.0f}",
              "data.raw_shape_min": f"{pr['source_H'][0]}x{pr['source_W'][0]}",
              "data.raw_shape_max": f"{pr['source_H'][2]}x{pr['source_W'][2]}",
              "data.raw_shape_med": f"{pr['source_H'][1]}x{pr['source_W'][1]}"}
        for s_ in ("train", "val", "test"):
            V[f"data.lab_{s_}"] = f"{pr['labeled']['split_counts'][s_]:,}"
            V[f"data.unlab_{s_}"] = f"{pr['unlabeled']['split_counts'][s_]:,}"
            V[f"data.lots_{s_}"] = f"{pr['lot_split_counts'][s_]:,}"
        for c in CLASSES_9:
            V[f"data.n_{c}"] = f"{pr['class_counts'][c]:,}"
    if best:
        ml, c9 = best["test"]["multilabel_8"], best["test"]["class9"]
        V |= {"best.macro_f1": f(ml["macro_f1"]), "best.micro_f1": f(ml["micro_f1"]),
              "best.weighted_f1": f(ml["weighted_f1"]),
              "best.macro_f1_9": f(c9["macro_f1"]),
              "best.weighted_f1_9": f(c9["weighted_f1"]),
              "best.acc_9": f(c9["accuracy"], 4),
              "best.any_defect_f1": f(best["test"]["any_defect"]["f1"]),
              "best.n_params": f"{best['n_params']:,}",
              "best.wall_min": f"{best['wall_min']:.0f}",
              "best.epochs": str(best["args"]["epochs"]),
              "best.width": str(best["args"]["width"]),
              "best.n_test": f"{best['test']['n']:,}",
              "best.tag": best_tag or "-"}
        for c in DEFECT_CLASSES:
            V[f"best.f1_{c}"] = f(ml["per_class"][c]["f1"])
            V[f"best.n_{c}"] = f"{ml['per_class'][c]['support']:,}"
        V["best.f1_none"] = f(c9["per_class"]["none"]["f1"])
        C = best["test"]["confusion"]
        for i, c in enumerate(CLASSES_9):
            if i:                      # how much of each class leaks into `none`
                V[f"cm.{c}.none"] = f"{100 * C[i][0] / max(sum(C[i]), 1):.0f}%"
    if sel.get("seed_spread"):
        ss = sel["seed_spread"]
        V |= {"seed.n": str(ss["n_seeds"]),
              "seed.macro_mean": f(ss["test_macro_f1_mean"]),
              "seed.macro_range": f(ss["test_macro_f1_range"]),
              "seed.wtd_mean": f(ss["test_weighted_f1_9_mean"], 4),
              "seed.wtd_range": f(ss["test_weighted_f1_9_range"], 4)}
    if sweep_rows:
        # the spread that matters is across the *loss/sampling* variants; the
        # no-augmentation row is a different question and is quoted separately
        aug_rows = [float(r[3]) for r in sweep_rows if "no augmentation" not in r[0]]
        V["sweep.spread"] = f(max(aug_rows) - min(aug_rows))
        V["sweep.best"] = f(max(aug_rows))
        noaug = [r for r in sweep_rows if "no augmentation" in r[0]]
        if noaug:
            V["sweep.noaug_macro"] = noaug[0][3]
            V["sweep.noaug_gap"] = f(max(aug_rows) - float(noaug[0][3]))
    if gc:
        m_ = gc["mean"]
        V |= {"cam.lift": f"{m_['top10_cam_fail_lift']:.2f}",
              "cam.mass_lift": f"{m_['fail_die_lift']:.2f}",
              "cam.peak": f"{m_['peak_on_failed_die']:.2f}",
              "cam.peak_chance": f"{m_['peak_chance']:.2f}",
              "cam.del": f(m_["deletion_drop_cam"]),
              "cam.del_rand": f(m_["deletion_drop_random"]),
              "cam.del_ratio": f"{m_['deletion_ratio']:.1f}",
              "cam.centroid": f(m_["centroid_err_radii"], 2),
              "cam.centroid_null": f(m_["centroid_err_null_radii"], 2),
              "cam.rcorr": f"{m_['r_corr_over_classes']:+.2f}",
              "cam.n": f"{sum(r['n'] for r in gc['per_class'].values()):,}"}
        for c, r in gc["per_class"].items():
            V[f"cam.lift_{c}"] = f"{r['top10_cam_fail_lift']:.2f}"
            V[f"cam.del_{c}"] = f(r["deletion_drop_cam"])
    if cl:
        V |= {"clu.n_fit": f"{cl['n_fit']:,}",
              "clu.n_pool": f"{cl['n_unlabeled_train_pool']:,}",
              "clu.n_eval": f"{cl['n_eval_labeled_test']:,}",
              "clu.majority": f(cl["majority_baseline"], 3)}
        for enc in cl["encoders"]:
            ks = sorted(cl["encoders"][enc]["k"], key=int)
            bk = max(ks, key=lambda k: cl["encoders"][enc]["k"][k]["purity_defect_only"])
            e = cl["encoders"][enc]["k"][bk]
            V |= {f"clu.{enc}.best_k": bk,
                  f"clu.{enc}.purity": f(e["purity"], 3),
                  f"clu.{enc}.purity_defect": f(e["purity_defect_only"], 3),
                  f"clu.{enc}.chance_defect": f(e["purity_defect_only_chance"], 3),
                  f"clu.{enc}.nmi": f(e["nmi"], 3),
                  f"clu.{enc}.nmi_defect": f(e["nmi_defect_only"], 3),
                  f"clu.{enc}.purity_k9": f(cl["encoders"][enc]["k"]["9"]["purity"], 3),
                  f"clu.{enc}.purity_defect_k9":
                      f(cl["encoders"][enc]["k"]["9"]["purity_defect_only"], 3)}
            for kk in ("9", "16", "32", "64", "128"):
                if kk in cl["encoders"][enc]["k"]:
                    V[f"clu.{enc}.pd_k{kk}"] = f(
                        cl["encoders"][enc]["k"][kk]["purity_defect_only"], 3)
        for kk in ("32", "128"):
            if "simclr" in cl["encoders"] and kk in cl["encoders"]["simclr"]["k"]:
                V[f"aug.all.k{kk}"] = f(
                    cl["encoders"]["simclr"]["k"][kk]["purity_defect_only"], 3)
    ca = jload(R / "cluster_aug.json")
    if ca:
        for enc in ca["encoders"]:
            for kk in ("32", "128"):
                if kk in ca["encoders"][enc]["k"]:
                    V[f"aug.{enc}.k{kk}"] = f(
                        ca["encoders"][enc]["k"][kk]["purity_defect_only"], 3)
    if lf:
        for m_ in lf:
            for fr, v in lf[m_].items():
                V[f"lf.{m_}.{fr}"] = f(v["test_macro_f1"])
                V[f"lf.n.{fr}"] = f"{v['n_train_labels']:,}"
    if ssl:
        V |= {"ssl.n": f"{ssl.get('n_unlabeled_train', 0):,}",
              "ssl.min": f"{ssl.get('wall_min', 0):.0f}",
              "ssl.epochs": str(ssl.get("args", {}).get("epochs", "?"))}

    text = tmpl.read_text()
    for k, v in V.items():
        text = text.replace("{{" + k + "}}", str(v))
    import re
    holes = sorted(set(re.findall(r"\{\{([^}]+)\}\}", text)))
    if holes:
        raise SystemExit("README.tmpl.md has unfilled holes: " + ", ".join(holes))
    Path("README.md").write_text(text)
    print("wrote README.md from README.tmpl.md", len(V), "values substituted")


if __name__ == "__main__":
    main()
